<div id="fist-location">
   <section class="pt-5 pb-5">
      <div class="container">
         <div class="row">
            <div class="card-container font-poppins col-xs-12 col-sm-4 mb-3">
               <div class="card">
                  <h4>Monthly Plan</h4>
                  <div class="card-table">
                     <p>29/mo</p>
                     <p>No setup fee</p>
                  </div>
                  <a class="btn btn-lg btn-gray-2 btn-block font-regular font-16" href="signup.aspx?plan=additional-location-monthly">Start My Monthly Plan</a>
               </div>
            </div><!-- #card-1 -->
            
            <div class="card-container card-popular col-xs-12 col-sm-4 mb-3">
               <div class="popular rounded-top">Most Popular</div>
               <div class="card">
                  <h4>Annual Plan</h4>
                  <div class="card-table">
                     <p>19/mo</p>
                     <p>No setup fee</p>
                  </div>
                  <a class="btn btn-lg btn-green btn-block font-regular font-16" href="signup.aspx?plan=additional-location-annual">Start My Annual Plan</a>
               </div>
            </div><!-- #card-2 -->            

            <div class="card-container font-poppins col-xs-12 col-sm-4 mb-3">
               <div class="card">
                  <h4>Two-Year Plan</h4>
                  <div class="card-table">
                     <p>14/mo</p>
                     <p>No setup fee</p>
                  </div>
                  <a class="btn btn-lg btn-gray-2" href="signup.aspx?plan=additional-location-two-year">Start My Two-Year Plan</a>
               </div>
            </div><!-- #card-3 -->

            <div class="card-info col-xs-12 col-md-12 text-center poppins-regular border-bottom mt-4 mt-md-5">
               <p class="mb-3 poppins-semibold text-gray-2">Annual and Two-Year plans paid up-front.</p>
<!--           <p class="mb-1">Optional Credit Card Processing</p>
               <p class="mb-0 pb-5">We offer a variety of plans, tailored to your needs. Click Here for more information.</p>
-->
			</div>
         </div>
      </div>
   </section>
   
   <section class="pt-0">
      <div class="container">
         <div class="row">
            <div class="feature-pad col-12">
               <div class="table-responsive text-center">
                  <table class="table table-striped border-bottom">
                     <thead>
                        <tr>
                           <th class="h3 poppins-semibold text-gray-2 pt-0">What you get</th>
                        </tr>
                     </thead>
                     <tbody>
                        <tr>
                           <th scope="row">Everything listed in the first location*.</th>
                        </tr>
                        <tr>
                           <th scope="row">Multiple locations listings, searchable by geo location.</th>
                        </tr>
                        <tr>
                           <th scope="row">Default location setting.</th>
                        </tr>
                     </tbody>
                  </table>
                  <p class="col-xs-12 col-md-10 offset-md-1 poppins-regular font-12 pt-4">*If you wish to use BigHoller's Elite Online Ordering System for additional locations, pricing for the next additional 4 locations are the same as the first location. If you have 5 or more locations, please call or contact us.</p>
               </div>
            </div>
         </div>
      </div>
   </section>
</div>