<div id="fist-location">
   <section class="pt-5 pb-5">
      <div class="container">
         <div class="row">
            <div class="card-container font-poppins col-xs-12 col-sm-4 mb-3">
               <div class="card">
                  <h4>Starter Plan</h4>
                  <div class="card-table">
                     <p>109/mo</p>
                     <p>+ $299 setup</p>
                     <p>1800 texts /mo</p>
                     <p>600 emails parsed /mo</p>
                  </div>
                  <a class="btn btn-lg btn-gray-2 btn-block font-regular font-16" href="signup.aspx?plan=data-digit-monthly">Start Starter Plan</a>
               </div>
            </div><!-- #card-1 -->
            
            <div class="card-container card-popular col-xs-12 col-sm-4 mb-3">
               <div class="popular rounded-top">Most Popular</div>
               <div class="card">
                  <h4>Premium Plan</h4>
                  <div class="card-table">
                     <p>129/mo</p>
                     <p>+ $399 setup</p>
                     <p>2700 texts /mo</p>
                     <p>900 emails parsed /mo</p>
                  </div>
                  <a class="btn btn-lg btn-green btn-block font-regular font-16" href="signup.aspx?plan=data-digit-annual">Start My Annual Plan</a>
               </div>
            </div><!-- #card-2 -->            

            <div class="card-container font-poppins col-xs-12 col-sm-4 mb-3">
               <div class="card">
                  <h4>Pro Plan</h4>
                  <div class="card-table">
                     <p>179/mo</p>
                     <p>+ $399 setup</p>
                     <p>5400 texts /mo</p>
                     <p>1800 emails parsed /mo</p>
                  </div>
                  <a class="btn btn-lg btn-gray-2" href="signup.aspx?plan=data-digit-two-year">Start My Two-Year Plan</a>
               </div>
            </div><!-- #card-3 -->
         </div>
      </div>
   </section>
   
   <section class="pt-0">
      <div class="container">
         <div class="row">
            <div class="feature-pad col-12">
               <div class="table-responsive text-center">
                  <table class="table table-striped border-bottom">
                     <thead>
                        <tr>
                           <th class="h3 poppins-semibold text-gray-2 pt-0">What you get</th>
                        </tr>
                     </thead>
                     <tbody>
                        <tr>
                           <th scope="row">Everything listed in the first location & additional locations.</th>
                        </tr>
                        <tr>
                           <th scope="row">Convert customers using third party companies like GrubHub, Uber Eats, etc., to loyal customers where you STOP PAYING a large per order fee.</th>
                        </tr>
                        <tr>
                           <th scope="row">Energize your existing customer based and increase their ordering frequency.</th>
                        </tr>
                        <tr>
                           <th scope="row">Build your social presence without advertizing expenditures.</th>
                        </tr>
                        <tr>
                           <th scope="row">Foster a deeper relationship with your customers.</th>
                        </tr>
                     </tbody>
                  </table>
<!--              <p class="col-xs-12 col-md-10 offset-md-1 poppins-regular font-12 pt-4">Restaurant App Notification powered by Data Digits marketing, driving more orders and cheaper orders.</p> -->
               </div>
            </div>
         </div>
      </div>
   </section>
</div>