<div id="fist-location">
   <section class="pt-5 pb-5">
      <div class="container">
         <div class="row">
            <div class="card-container font-poppins col-xs-12 col-sm-4 mb-3">
               <div class="card">
                  <h4>Monthly Plan</h4>
                  <div class="card-table">
                     <p>$109/mo</p>
                     <p>+ $299 setup</p>
<!--                 <p>+ Apple Mandated $99/year fee</p> -->
                  </div>
                  <a class="btn btn-lg btn-gray-2 btn-block font-regular font-16" href="signup.aspx?plan=first-location-monthly">Start My Monthly Plan</a>
               </div>
            </div><!-- #card-1 -->
            
            <div class="card-container card-popular col-xs-12 col-sm-4 mb-3">
               <div class="popular rounded-top">Most Popular</div>
               <div class="card">
                  <h4>Annual Plan</h4>
                  <div class="card-table">
                     <p>$89/mo</p>
                     <p>+ $149 setup</p>
<!--                 <p>+ Apple Mandated $99/year fee</p> -->
                  </div>
                  <a class="btn btn-lg btn-green btn-block font-regular font-16" href="signup.aspx?plan=first-location-annual">Start My Annual Plan</a>
               </div>
            </div><!-- #card-2 -->            

            <div class="card-container font-poppins col-xs-12 col-sm-4 mb-3">
               <div class="card">
                  <h4>Two-Year Plan</h4>
                  <div class="card-table">
                     <p>$79/mo</p>
                     <p>+ $119 setup</p>
<!--                 <p>+ Apple Mandated $99/year fee</p> -->
                  </div>
                  <a class="btn btn-lg btn-gray-2" href="signup.aspx?plan=first-location-two-year">Start My Two-Year Plan</a>
               </div>
            </div><!-- #card-3 -->

            <div class="card-info col-xs-12 col-md-12 text-center poppins-regular border-bottom mt-4 mt-md-5">
               <p class="mb-3 poppins-semibold text-gray-2">Annual and Two-Year plans paid up-front.</p>
            </div>
         </div>
      </div>
   </section>
   
   <section class="pt-0">
      <div class="container">
         <div class="row">
            <div class="feature-pad col-12">
               <div class="table-responsive text-center">
                  <table class="table table-striped">
                     <thead>
                        <tr>
                           <th class="h3 poppins-semibold text-gray-2 pt-0">What you get</th>
                        </tr>
                     </thead>
                     <tbody>
                        <tr>
                           <th scope="row">Online Ordering - Your Choice - SEE BELOW</th>
                        </tr>
                        <tr>
                           <th scope="row">Loyalty Program - keep your customers engaged with a program you can tailor.</th>
                        </tr>
                        <tr>
                           <th scope="row">Your logo, your colors - your app will be unique to your brand.</th>
                        </tr>
                        <tr>
                           <th scope="row">Your gallery - pictures featuring your food, your location.</th>
                        </tr>
                        <tr>
                           <th scope="row">Menus - Display all your different menus. Expandable for easy viewing.</th>
                        </tr>
                           <th scope="row">Ratings & reviews provided real time. Optionally displayed at your request.</th>
                        </tr>
                        <tr>
                           <th scope="row">Restaurant address and other contact information.</th>
                        </tr>
                        <tr>
                           <th scope="row">Restaurant hours including user notification if a restaurant is opened or closed.</th>
                        </tr>
                        <tr>
                           <th scope="row">Website link.</th>
                        </tr>
                        <tr>
                           <th scope="row">Driving direction via user choice or Waze, Apple or Google.</th>
                        </tr>
                        <tr>
                           <th scope="row"> Social Media Links.</th>
                        </tr>
                     </tbody>
                  </table>
               </div>
            </div>
         </div>
      </div>
   </section>

      <section class="pt-0">
      <div class="container">
         <div class="row">
            <div class="feature-pad col-12">
               <div class="table-responsive text-center">
                  <table class="table table-striped">
                     <thead>
                        <tr>
                           <th class="h3 poppins-semibold text-gray-2 pt-0">Online Ordering - Your Choice</th>
                        </tr>
                     </thead>
                     <tbody>
                        <tr>
                           <th scope="row">Choose BigHoller's Elite Online Ordering or any Online Ordering Company of your Choice.</th>
                        </tr>
                        <tr>
                           <th scope="row">BigHoller's Elite Online Ordering has over 200 features with the best mobile online ordering interface at the fastest speeds amongst all its competitors.</th>
                        </tr>
                        <tr>
                           <th scope="row">We can also link to multiple online ordering links if you require it.</th>
                        </tr>
                     </tbody>
                  </table>
               </div>
            </div>
         </div>
      </div>
   </section>



</div>