<section id="callout-card" class="pt-0 pb-0">
    <div class="background-shape background-shape-top-1" data-negative="false">
		<svg preserveAspectRatio="none" viewBox="0 0 1000 100" xmlns="http://www.w3.org/2000/svg"><path class="background-shape-fill" fill="rgba(42, 171, 228, 0.15)" d="M0,6V0h1000v100L0,6z"></path></svg>
	</div><!-- #background-shape-top -->

	<div class="section-inner">
    	<div class="container">
         	<div class="row">
                <div class="col-xs-12 col-md-12 col-lg-8 offset-lg-2">
                   <div class="card card-2">
                      <div class="pt-3 pb-3 text-center">
                         <h4 class="poppins-medium mb-3">It starts with a restaurant app</h4>
                         <p class="poppins-regular mb-3">Learn about our full suite of digital marketing tools for restaurants.</p>
                      </div>
                   </div>
                </div>
         	</div><!-- row -->
      	</div><!-- container -->
  	</div><!-- section-inner -->

    <div class="background-shape background-shape-bottom" data-negative="false">
		    <svg preserveAspectRatio="none" viewBox="0 0 1000 100" xmlns="http://www.w3.org/2000/svg"><path class="background-shape-fill" fill="rgba(42, 171, 228, 0.15)" d="M0,6V0h1000v100L0,6z"></path></svg>
	</div><!-- #background-shape-bottom -->
</section><!-- #callout-card -->