<section id="prime-cta" class="pt-0 pb-0">
	<div class="svg-mask-container">
		<div class="svg-mask">
			<svg width="100%" height="100%" viewBox="0 0 100 100" preserveAspectRatio="none">
				<path d="M0 100 L 0 0 C 25 100 75 100 100 0 L 100 100" id="bottom-curve" fill="#fff"></path>
			</svg>
		</div>
	</div>
	<div class="section-inner pt-5 pb-5">
		<div class="container">
			<div class="row">
				<h3 class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-12 offset-md-0 pt-0 pt-md-5 mb-5 text-center text-white">Put the power of BigHoller to work for you</h3>
				<div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-8 offset-md-2 col-lg-4 offset-lg-4 mb-md-5">
					<a class="btn btn-lg btn-block btn-white-2 poppins-medium font-16" href="product.aspx">See how it works</a>
				</div>
         	</div><!-- row -->
      	</div><!-- container -->
	</div><!-- #section-inner -->
</section><!-- #prime-cta -->