<section id="main-footer" class="footer-2 background-gray-2">
    <div class="container">
        <div class="row">
           <ul class="footer-list-container list-unstyled col-6 col-md-4">
                <li>
                   <p class="footer-links-title font-14 poppins-bold font-caps text-white">Bigholler</p>
                </li>
                <li><a href="product.aspx" class="footer-links">Product</a></li>
                <li><a href="pricing.aspx" class="footer-links">Pricing</a></li>
                <li><a href="ccard-process.aspx" class="footer-links">Credit Card Processing</a></li>
          </ul><!-- #discover -->

           <ul class="footer-list-container list-unstyled col-6 col-md-4">
                <li>
                   <p class="footer-links-title font-14 poppins-bold font-caps text-white">Company</p>
                </li>
                <li><a href="about.aspx" class="footer-links">About Us</a></li>
                <li><a href="contact-reseller.aspx" class="footer-links">Referral Program</a></li>
                <li><a href="contact-reseller.aspx" class="footer-links">Reseller Program</a></li>
                <li><a href="contact-partners.aspx" class="footer-links">Partners</a></li>
                <li><a href="https://get.teamviewer.com/bighollersupport" class="footer-links">Remote Support</a></li>
                <li><a href="contact-support.aspx" class="footer-links">Contact Us</a></li>
           </ul>
           <!-- #company -->
            
            <div class="footer-list-container col-12 col-md-4">
                <p class="footer-links">&copy; 2020 BigHoller.com LLC Terms & Privacy Policy.
                  <span><a href="terms-of-use.aspx" class="footer-links text-underline">Terms of Use</a> &amp; <a href="privacy-policy.aspx" class="footer-links text-underline">Privacy Policy</a></span>
               </p>
            </div>
        </div><!-- #row -->
    </div><!-- #container -->
</section>