<header id="header" class="header header-3 background-gray-2">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="col-12 pl-0 pl-md-3 pr-0 pr-md-3 d-flex">
                    <div class="logo float-left">
                        <a href="index.aspx">
                            <img srcset="img/logo-white1x.png 1x, img/logo-white2x.png 2x, img/logo-white3x.png 3x, img/logo-white4x.png 4x," width="110" height="60" alt="Bigholler" />
                        </a>
                    </div><!-- #logo -->

                    <nav class="main-nav col d-none d-lg-inline-block float-lg-right">
                        <ul class="float-right poppins-semibold">
                            <li class="product-link"><a href="product.aspx">Product</a></li>
                            <li class="about-link"><a href="about.aspx">About</a></li>
                            <li class="pricing-link"><a href="pricing.aspx">Pricing</a></li>
                            <li class="contact-link"><a href="contact.aspx">Contact</a></li>
                        </ul>
                    </nav><!-- #main-nav-large-screens -->

                    <div class="button-container d-none d-lg-inline-block pt-4 pb-4">
                        <a href="pricing.aspx" class="btn btn-white-3 font-13 float-right pl-4 pr-4">Get Started</a>
                    </div><!-- #order-now-button -->

                    <div class="d-lg-none d-inline-block float-right">
                        <div class="mobile-nav-trigger">
                            <span></span>
                            <span></span>
                            <span></span>
                            <span></span>
                        </div>
                    </div><!-- #mobile-nav-trigger -->
                </div>
            </div>
        </div><!-- #row -->
    </div><!-- #container -->
</header><!-- #header -->