<section class="intro pt-5 pb-2">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-12 col-md-10 offset-md-1 col-lg-6 offset-lg-0">
                <video class="embed-responsive d-none d-lg-block" poster="./assets/hungry-brain-poster-com.png" muted autoplay loop src="./assets/hungry-brain.mp4">
                    Your browser does not support the HTML5 Video element.
                </video><!-- #intro-video -->
                <img class="img-responsive d-block d-lg-none" src="./assets/hungry-brain-poster-com.png"><!-- #intro-img -->
            </div>
            <div class="col-12 col-lg-6 text-center-mobile">
                <h1 class="h3 poppins-regular text-blue mb-5">"Our restaurant apps are driving customers to your door."</h1>

                <div class="col-8 offset-2 col-md-6 offset-md-3 offset-lg-0 pl-0 pr-0">
                    <a class="btn btn-lg btn-blue btn-block font-16 poppins-medium" href="product.aspx">See how it works</a>
                </div>
            </div><!-- #intro-content -->
        </div><!-- #row -->
    </div><!-- #container -->
</section><!-- #intro -->