<nav class="main-nav d-lg-none">
    <ul class="poppins-medium font-14 mb-4">
		<li class="product-link"><a href="product.aspx">Product</a></li>
		<li class="about-link"><a href="about.aspx">About</a></li>
		<li class="pricing-link"><a href="pricing.aspx">Pricing</a></li>
		<li class="contact-link"><a href="contact.aspx">Contact</a></li>
    </ul>
    <a href="pricing.aspx" class="btn btn-blue btn-md btn-block">Get Started</a>
</nav><!-- #main-nav-mobile-screens -->