<section id="our-customers">
  	<div class="container">
 		<div class="row">
            <div class="col-12 text-center">
               <h3 class="mb-5">Meet just a few of our customers</h3>
               	<div class="col-12 mb-5">
                  	<div class="col-12">
						<div class="col-3 col-sm-3 col-sm-offset-1 col-md-3 col-lg-3 logo-pad">
							<img class="img-responsive logo vcentered-hcentered-content" alt="Logo" src="./img/brands/pakulas-com.png">
						</div>

						<div class="col-3 col-sm-3 col-md-3 col-lg-3 logo-pad">
							<img class="img-responsive logo vcentered-hcentered-content ibm-fix" alt="Logo" src="./img/brands/wingsthings.png">
						</div>

						<div class="col-3 col-sm-3 col-md-3 col-lg-3 logo-pad">
							<img class="img-responsive logo bmw-fix vcentered-hcentered-content" alt="Logo" src="./img/brands/amys.png">
						</div>

						<div class="col-3 col-sm-3 col-md-3 col-lg-3 logo-pad">
							<img class="img-responsive logo vcentered-hcentered-content" alt="Logo" src="./img/brands/yardsgourmey.png">
						</div>

						<div class="col-3 col-sm-3 col-md-3 col-lg-3 logo-pad">
							<img class="img-responsive logo vcentered-hcentered-content" alt="Logo" src="./img/brands/fairfield.png">
						</div>

						<div class="col-3 col-sm-3 col-md-3 col-lg-3 logo-pad">
							<img class="img-responsive logo vcentered-hcentered-content" alt="Logo" src="./img/brands/trattoria632.png">
						</div>
                  	</div>
               	</div>
            </div>
 		</div><!-- #row -->
  	</div><!-- #container -->
</section><!-- #our-customers-section -->