<section class="page-header-section clearfix">
    <div class="container">
        <div class="row">
            <div class="page-header-content jumbotron text-justify-center col-12">
                <h1 class="font-weight-bold">About Us</h1>
                <p class="title-description">Get to know us more</p>
            </div><!-- #page-header-content -->
        </div><!-- #row -->
    </div><!-- #container -->
</section><!-- #page-header-section -->