<section id="quick-start" class="pt-5 pb-5">
    <div class="background-shape background-shape-top-1" data-negative="false">
      <svg preserveAspectRatio="none" viewBox="0 0 1000 100" xmlns="http://www.w3.org/2000/svg"><path class="background-shape-fill" fill="rgba(42, 171, 228, 0.04)" d="M0,6V0h1000v100L0,6z"></path></svg>
    </div><!-- #background-shape-top -->

    <div class="section-inner">
      	<div class="container">
            <div class="row text-center">
                <div class="col-10 offset-1 col-md-12 offset-md-0 mt-5 mb-5">
                   <h2 class="h3 mb-5">It all starts with a restaurant app</h2>
                </div>
            </div>

         	<div class="row align-items-center text-center-mobile">
              <div class="col-10 offset-1 col-sm-10 offset-sm-1 d-block d-lg-none mb-4">
                  <div class="row align-items-center">
                      <div class="col-4 animated"><img class="img-responsive btm-30" src="./img/stone-fired-pizza-main.png"></div>
                      <div class="col-4 animated">
                          <img class="img-responsive mb-4" src="./img/stone-fired-pizza-menu.png">
                      </div>
                      <div class="col-4 animated"><img class="img-responsive" src="./img/stone-fired-pizza-ordering.png"></div>
                    </div>
                </div>

                <div class="col-12 col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-5 offset-lg-0 mobile-text-center mb-4 mb-lg-0">
                   <h3 class="poppins-medium mb-4">Quick to start</h3>
                   <p class="poppins-regular">With our restaurant app templates, state of the art technology framework, and a ready to go staff, we’ll have you up and running in no time.</p>
                </div>

              <div class="col-12 col-md-7 d-none d-lg-block">
    				      <div class="row align-items-center">
                     	<div class="col-3 offset-lg-2 animated"><img class="img-responsive btm-30" src="./img/stone-fired-pizza-main.png"></div>
                     	<div class="col-3 animated">
                          <img class="img-responsive mb-4" src="./img/stone-fired-pizza-driving-directions.png">
                          <img class="img-responsive" src="./img/stone-fired-pizza-menu.png">
                      </div>
                     	<div class="col-3 animated"><img class="img-responsive" src="./img/stone-fired-pizza-ordering.png"></div>
                   	</div>
                </div>
            </div><!-- #row -->
      	</div><!-- #container -->
    </div><!-- #section-inner -->

    <div class="background-shape background-shape-bottom" data-negative="false">
        <svg preserveAspectRatio="none" viewBox="0 0 1000 100" xmlns="http://www.w3.org/2000/svg"><path class="background-shape-fill" fill="rgba(42, 171, 228, 0.04)" d="M0,6V0h1000v100L0,6z"></path></svg>
  </div><!-- #background-shape-bottom -->
</section><!-- #quick-start-section -->