<section id="quick-impact">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-12 col-md-8 offset-md-2 d-block d-none d-md-block d-block d-lg-none text-center">
                <div class="impact-img mb-5 mb-lg-0">
                    <img class="img-responsive radius-circle hidden-md hidden-lg" src="./img/edison-diner-held-in-hand.jpg" alt="Present">
                </div>
            </div>

            <div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-10 offset-md-1 col-lg-4 offset-lg-1">
             	  <div class="text-center-mobile">
                    <h3 class="poppins-medium mb-4">Quick to make an impact</h3>
                    <p class="poppins-regular">Nothing else looks like a BigHoller restaurant app. And no other restaurant app is as engaging, persuasive, and memorable.</p>
             	</div>
            </div>

            <div class="col-12 col-md-8 offset-md-2 col-lg-6 offset-lg-0 d-none d-sm-none d-lg-block text-center">
                <div class="impact-img mb-5 mb-lg-0">
                    <img class="img-responsive radius-circle hidden-md hidden-lg" src="./img/edison-diner-held-in-hand.jpg" alt="Present">
                </div>
            </div>
        </div><!-- #row -->
    </div><!-- #container -->
 </section><!-- #quick-impact-section -->