<section id="quick-customize">
  	<div class="container">
     	<div class="row align-items-center">
            <div class="col-12 col-md-8 offset-md-2 col-lg-7 offset-lg-0 text-center">
               <div class="impact-img mb-5 mb-lg-0">
                  <img class="img-responsive hidden-md hidden-lg" src="./img/edison-diner-three-app-images.png" alt="Present">
               </div>
            </div>
            
            <div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-10 offset-md-1 col-lg-5 offset-lg-0">
               	<div class="text-center-mobile">
                  	<h3 class="poppins-medium mb-4">Quick to customize</h3>
                  	<p class="poppins-regular">Our team and smart bots will use your readily available images to make your restaurant app a unique experience.</p>
               	</div>
            </div>
     	</div><!-- #row -->
  	</div><!-- #container -->
</section><!-- #quick-to-customize -->