<div id="signup-first-step">
   <section class="pt-0">
      <div class="container">
         <div class="row">
            <div class="col-xs-12 col-md-6 offset-md-3">
               <form>
                 <div class="form-group" novalidate>
                   <input type="text" class="form-control" id="InputFirstName" aria-describedby="firstname" placeholder="First Name">
                 </div>                 
                 <div class="form-group">
                   <input type="text" class="form-control" id="InputLastName" aria-describedby="lastname" placeholder="Last Name">
                 </div>                 
                 <div class="form-group">
                   <input type="email" class="form-control" id="InputEmail" aria-describedby="email" placeholder="Enter email">
                 </div>
                 <div class="form-group">
                   <input type="password" class="form-control" id="InputPassword" placeholder="Password">
                 </div>                 
                 <button type="submit" class="btn btn-blue btn-block btn-primary" data-target="#carouselIndicators" data-slide-to="1">Continue</button>
               </form>
            </div>
         </div>
      </div>
   </section>
</div>