<section id="testimonial" class="blob-shape-1">
    <div class="container">
        <div class="row">
            <div class="col-6 offset-2 col-md-4 offset-md-4 col-lg-2 offset-lg-4 mx-auto"><img class="img-responsive" src="./img/pizza-1.png"></div>

            <div class="col-xs-12 col-sm-10 offset-sm-1 col-md-10 offset-md-1 col-lg-10 offset-lg-1 text-center">
                <img class="col-5 col-md-2 mb-4" alt="Stone Fired Pizza" src="./img/stonefiredpizza-quote-com.png">
                <div class="h2 poppins-light mb-3"><q>BigHoller is helping to reinvent the art of customer communication.</q></div>
                <div class="p poppins-regular font-18"><span class="poppins-semibold">Don Lemay, </span>Owner</div>
            </div>
        </div><!-- #row -->
    </div><!-- #container -->
</section><!-- #testimonial-section -->